---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        image: mayurikulkarni2024/payment-ms:latest
        ports:
        - containerPort: 8081
        envFrom:
            - configMapRef:
                name: payment-ms-config